@startuml UC07_Solicitar_Impresion
title UC-07: Solicitar Impresión

skinparam monochrome true
skinparam shadowing false
skinparam backgroundColor white

left to right direction

actor "Solicitante" as S

rectangle "Sistema Braille Inclusivo" {
    usecase "Confirmar diseño y solicitar" as UC07a
    usecase "Seleccionar recurso del catálogo" as UC07b
    usecase "Registrar solicitud" as UC07c
    usecase "Calcular consumo PLA (gramos)" as UC07d
    usecase "Estimar costo de producción" as UC07e
    usecase "Generar coordenadas G-Code (X,Y,Z)" as UC07f
    usecase "Compilar archivo .gcode" as UC07g
    usecase "Asignar estado 'Pendiente'" as UC07h
    usecase "Mostrar confirmación" as UC07i
    usecase "Ver mis solicitudes" as UC07j
    usecase "Cancelar solicitud (solo Pendiente)" as UC07k
}

S --> UC07a
S --> UC07b
S --> UC07j
S --> UC07k

UC07a ..> UC07c : <<include>>
UC07c ..> UC07d : <<include>>
UC07c ..> UC07e : <<include>>
UC07d ..> UC07f : <<include>>
UC07f ..> UC07g : <<include>>
UC07c ..> UC07h : <<include>>
UC07h ..> UC07i : <<include>>
UC07c ..> UC07b : <<extend>>

@enduml
